name: AntiIllegalRecode
main: me.tiger.antiIllegalRecode.AntiIllegalRecode
version: 2.3
api-version: 1.21
commands:
  airecode:
    description: Enable or disable the AntiIllegalRecode plugin
    usage: /airecode <enable|disable>
